CREATE TABLE connection
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_id  BIGINT                                  NOT NULL,
    end_id    BIGINT                                  NOT NULL,
    departure SMALLINT                                NOT NULL,
    arrival   SMALLINT,
    trip_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_connection PRIMARY KEY (id)
);

CREATE TABLE station
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    uic_code  VARCHAR(255),
    country   VARCHAR(255)                            NOT NULL,
    latitude  DECIMAL,
    longitude DECIMAL,
    CONSTRAINT pk_station PRIMARY KEY (id)
);

CREATE TABLE station_local_code
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    station_id BIGINT                                  NOT NULL,
    country    VARCHAR(255)                            NOT NULL,
    local_code VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_stationlocalcode PRIMARY KEY (id)
);

CREATE TABLE trip
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company    VARCHAR(255),
    type       VARCHAR(255),
    identifier VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_trip PRIMARY KEY (id)
);

CREATE TABLE trip_validity
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    trip_id BIGINT,
    date    date,
    CONSTRAINT pk_tripvalidity PRIMARY KEY (id)
);

ALTER TABLE station_local_code
    ADD CONSTRAINT station_local_code_unique_country_local_code UNIQUE (country, local_code);

ALTER TABLE station
    ADD CONSTRAINT uc_station_uiccode UNIQUE (uic_code);

CREATE INDEX IDX_STATION_UICCODE ON station (uic_code);

ALTER TABLE connection
    ADD CONSTRAINT FK_CONNECTION_ON_END FOREIGN KEY (end_id) REFERENCES station (id);

ALTER TABLE connection
    ADD CONSTRAINT FK_CONNECTION_ON_START FOREIGN KEY (start_id) REFERENCES station (id);

ALTER TABLE connection
    ADD CONSTRAINT FK_CONNECTION_ON_TRIP FOREIGN KEY (trip_id) REFERENCES trip (id);

ALTER TABLE station_local_code
    ADD CONSTRAINT FK_STATIONLOCALCODE_ON_STATION FOREIGN KEY (station_id) REFERENCES station (id);

ALTER TABLE trip_validity
    ADD CONSTRAINT FK_TRIPVALIDITY_ON_TRIP FOREIGN KEY (trip_id) REFERENCES trip (id);