CREATE TABLE connection
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_id  BIGINT                                  NOT NULL,
    end_id    BIGINT                                  NOT NULL,
    departure TIMESTAMP with time zone                NOT NULL,
    arrival   TIMESTAMP with time zone,
    trip_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_connection PRIMARY KEY (id)
);

CREATE TABLE trip
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identifier VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_trip PRIMARY KEY (id)
);

ALTER TABLE trip
    ADD CONSTRAINT uc_trip_identifier UNIQUE (identifier);

ALTER TABLE connection
    ADD CONSTRAINT FK_CONNECTION_ON_END FOREIGN KEY (end_id) REFERENCES station (id);

ALTER TABLE connection
    ADD CONSTRAINT FK_CONNECTION_ON_START FOREIGN KEY (start_id) REFERENCES station (id);

ALTER TABLE connection
    ADD CONSTRAINT FK_CONNECTION_ON_TRIP FOREIGN KEY (trip_id) REFERENCES trip (id);
