CREATE TABLE station_local_code
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    station_id BIGINT                                  NOT NULL,
    country    VARCHAR(255)                            NOT NULL,
    local_code VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_stationlocalcode PRIMARY KEY (id)
);

ALTER TABLE station_local_code
    ADD CONSTRAINT FK_STATIONLOCALCODE_ON_STATION FOREIGN KEY (station_id) REFERENCES station (id);

ALTER TABLE station
    DROP COLUMN local_code;

DROP INDEX IDX_STATION_UICCODE;

CREATE INDEX IDX_STATION_UICCODE ON station (uic_code);